# Generated by Django 3.2.9 on 2021-11-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_cardspending_cardtopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardspending',
            name='card_transactions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transactions.cardtransaction'),
        ),
    ]
