# Generated by Django 3.2.9 on 2021-11-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_cardspending_card_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtopup',
            name='card_transactions',
        ),
        migrations.RemoveField(
            model_name='cardtopup',
            name='company_transaction',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='companytransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companytransaction',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='restauranttransaction',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restauranttransaction',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='CardSpending',
        ),
        migrations.DeleteModel(
            name='CardTopup',
        ),
        migrations.DeleteModel(
            name='CardTransaction',
        ),
        migrations.DeleteModel(
            name='CompanyTransaction',
        ),
        migrations.DeleteModel(
            name='RestaurantTransaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
