# Generated by Django 3.2.9 on 2021-11-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20211109_1028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyfundingtransaction',
            name='amount_gt_0',
        ),
    ]
