# Generated by Django 3.2.9 on 2021-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('employees', models.ManyToManyField(to='companies.Employee')),
            ],
        ),
    ]
