# Generated by Django 3.2.9 on 2021-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20211104_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('small_town', 'Small Town'), ('city_center', 'City Center')], default='city_center', max_length=15),
            preserve_default=False,
        ),
    ]
