# Generated by Django 3.2.9 on 2021-11-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_employee_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.employee'),
        ),
    ]
